# iOS CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ios-migrating-from-1-2/ for more details
#
version: 2
jobs:
  build:
    # Specify the Xcode version to use
    macos:
      xcode: '9.4.1'

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Instal node modules
          command: yarn install

      # Run tests
      - run:
          name: Run tests
          command: yarn test
      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      # - store_test_results:
      #     path: test_output/report.xml
      # - store_artifacts:
      #     path: /tmp/test-results
      #     destination: scan-test-results
      # - store_artifacts:
      #     path: ~/Library/Logs/scan
      #     destination: scan-logs
